/// Flutter icons WindLevelIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WindLevelIcon
///      fonts:
///       - asset: fonts/WindLevelIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WindLevelIcon {
  WindLevelIcon._();

  static const _kFontFam = 'WindLevelIcon';
  static const String? _kFontPkg = null;

  static const IconData mid = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData min = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData max = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
