/// Flutter icons WindVIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WindVIcon
///      fonts:
///       - asset: fonts/WindVIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WindVIcon {
  WindVIcon._();

  static const _kFontFam = 'WindVIcon';
  static const String? _kFontPkg = null;

  static const IconData swing = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l0 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l5 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
